server:
  port: ${PORT:8080}

spring:
  application:
    name: financeira-moreira-api
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    show-sql: false
    open-in-view: false

callmebot:
  phone: ${CALLMEBOT_PHONE:}
  apikey: ${CALLMEBOT_APIKEY:}
